name: ncti
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  dotenv: ^4.1.0
  jwt_decode: ^0.3.1
  shared_preferences: ^2.0.20
  salomon_bottom_bar: ^3.3.2
  auto_route: ^6.3.0
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  json_annotation: ^4.8.0
  vector_graphics: ^1.1.5+1
  flutter_svg: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  provider: ^6.0.5  
 
  table_calendar: ^3.0.9  
  flutter_chat_ui: ^1.6.6
  # file_picker: ^5.3.0
  flutter_chat_types: ^3.6.0
  # image_picker: ^0.8.7+5
  uuid: ^3.0.7
  # open_filex: ^4.3.2
  path_provider: ^2.0.15
  web_socket_channel: ^2.4.0
  multi_select_flutter: ^4.1.3
 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  # lint: ^2.0.1

dependency_overrides:
  meta: ^1.7.0
  intl: any

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/test.png"
