name: ncti
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  dotenv: ^4.1.0
  jwt_decode: ^0.3.1
  shared_preferences: ^2.0.20
  salomon_bottom_bar: ^3.3.2
  auto_route: ^6.3.0
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  json_annotation: ^4.8.0
  vector_graphics: ^1.1.5+1
  flutter_svg: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  # flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  # lint: ^2.0.1

dependency_overrides:
  meta: ^1.7.0

flutter:

  uses-material-design: true


  assets:
  - assets/images/
  - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/test.png"
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: ""
#   adaptive_icon_maskable: true
#   icons:
#     - icon: "assets/images/icon.png"
#       date_text: "${DateTime.now().day}"
#       date_text_color: "#FFFFFF"
#       date_background_color: "#000000"