// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCZP2eqpzVxhj55C1pBr3wT7cKbm1Reus',
    appId: '1:653162188588:web:7eb96ea626407fb35aa689',
    messagingSenderId: '653162188588',
    projectId: 'ncti-906c7',
    authDomain: 'ncti-906c7.firebaseapp.com',
    storageBucket: 'ncti-906c7.appspot.com',
    measurementId: 'G-861ELV481C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhtl6ERSrsrprKQLTKQ_ydgj9R6FE0m8I',
    appId: '1:653162188588:android:e6acdd4701c6d8055aa689',
    messagingSenderId: '653162188588',
    projectId: 'ncti-906c7',
    storageBucket: 'ncti-906c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3zNH9KlRo6JG4gkaTKUHk5V_LdYdeoO4',
    appId: '1:653162188588:ios:c5e63cf1d4e24ebc5aa689',
    messagingSenderId: '653162188588',
    projectId: 'ncti-906c7',
    storageBucket: 'ncti-906c7.appspot.com',
    iosClientId: '653162188588-28ovosfuluptt7pvhfto05gdikjpebak.apps.googleusercontent.com',
    iosBundleId: 'com.example.ncti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3zNH9KlRo6JG4gkaTKUHk5V_LdYdeoO4',
    appId: '1:653162188588:ios:c5e63cf1d4e24ebc5aa689',
    messagingSenderId: '653162188588',
    projectId: 'ncti-906c7',
    storageBucket: 'ncti-906c7.appspot.com',
    iosClientId: '653162188588-28ovosfuluptt7pvhfto05gdikjpebak.apps.googleusercontent.com',
    iosBundleId: 'com.example.ncti',
  );
}
